### ISSUE TITLE
Automate specification update process

### ISSUE THREAD

**Issue by mre** [slack-ruby/slack-api-ref#12]
The Slack API is changing quite quickly. Manually triggering an update of the specification requires human intervention. Therefore it would be nice to automatically update the specification on a regular basis. One idea would be to have a bot with commit permissions to the repository that triggers a daily build.

The bot could run some sanity checks before commiting:
* did the `rake:update` task exit with 0?
* are the file sizes above a certain threshold (e.g. 500 bytes)?
* are all specification files valid JSON?
* do all method specification files contain the expected keys (e.g. `group`, `name`, `args`, etc.)?

We could use the [new Cronjob functionality of Travis CI](https://docs.travis-ci.com/user/cron-jobs/) for the bot. What do you think?

**Comment by dblock** [comment]
I think it's a great idea. Do you want to help out with this library @mre? Happy to invite you to collaborators and you could set this one up!

**Comment by mre** [comment]
That sounds great, yes!
Don't expect too much though because I'm not a Ruby Programmer. 😉

**Comment by dblock** [comment]
Done. Keep making pull requests for feedback as usual.

**Comment by mre** [comment]
Did some research on the automatic git push from travis and the majority of the work is already done in [ewanmellor/gh-publisher](https://github.com/ewanmellor/gh-publisher). Planning to add that if you also like this approach.

**Comment by dblock** [comment]
You actually don't need gh-publisher to push code, that's to push github pages. If the tests pass you can just `git push origin master`.

**Comment by dblock** [comment]
Closing via https://github.com/slack-ruby/slack-api-ref/pull/15.

**Comment by dblock** [comment]
Looks like https://travis-ci.org/slack-ruby/slack-api-ref cron broke, the token is no longer valid. Care to help @mre? Could use a doc on what kind of token that needs to be and where to get it from for next time it breaks (maybe a CRON.md :)).
