### ISSUE TITLE
Add undocumented methods

### ISSUE THREAD

**Issue by manuelmeurer** [slack-ruby/slack-api-ref#21]
I'd really like to use the [undocumented methods](https://github.com/ErikKalkoken/slackApiDoc) in the [Slack Ruby client](https://github.com/slack-ruby/slack-ruby-client). I added two of them [in my own fork](https://github.com/krautcomputing/slack-ruby-client/tree/undocumented-methods) for now but ideally, as @dblock mentioned in https://github.com/ErikKalkoken/slackApiDoc/issues/5, they should reside in this repo in JSON format.

* How/where should we add them?
* Should we scrape them from https://github.com/ErikKalkoken/slackApiDoc? This would mean we'd have to rely on the format of the Markdown files in that repo not to change...

@dblock I'm happy to work on this if you give me a quick tip what to do. 😄

**Comment by dblock** [comment]
This is a dup of #6.

**Comment by dblock** [comment]
I'll close it as a dup, but I will take any PR that accomplishes this. Maybe adding subfolders such as `undocumented` into each category and also loading from there when generating output?

**Comment by manuelmeurer** [comment]
Just to clarify - you mean adding `undocumented` folders here in `slack-api-ref`, not in https://github.com/krautcomputing/slack-ruby-client ([like this](https://github.com/krautcomputing/slack-ruby-client/commit/a4fc2ed4da5d70d44202efd45b829033af408074)), correct?

**Comment by dblock** [comment]
Yes, here. We want JSON documentation here and we want slack-ruby-client to pick it up, which can be a separate PR.
