### ISSUE TITLE
Add docs/examples for `oauth.v2.exchange`

### ISSUE THREAD

**Issue by davidcelis** [slack-ruby/slack-api-ref#63]
The `oauth.v2.exchange` method doesn't have any documentation or sample responses, making it difficult to reason through how it may behave differently or respond differently when exchanging bot tokens vs when exchanging user tokens. User tokens are often returned differently from Slack's API, usually nested within an `authed_user` object. Is it the same for `oauth.v2.exchange`? We have no way of knowing without testing it ourselves, which is difficult because tokens can only be exchanged once

**Comment by dblock** [comment]
The ref is just a scraper from Slack documentation to create machine-readable API references used in places like slack-ruby-client, so you're probably asking in the wrong place. Contact slack?

https://api.slack.com/methods/oauth.v2.exchange
